name: drivers_test
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^15.1.2
  cached_network_image: ^3.4.1
  flutter_svg: 2.1.0
  provider: ^6.1.5
  share_plus: ^11.0.0
  url_launcher: ^6.3.1
  permission_handler: ^12.0.0+1
  adaptive_dialog: ^2.4.1

  drift: ^2.26.1
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.5
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  build_runner: ^2.4.15
  drift_dev: ^2.13.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/json/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist-Regular.ttf
          weight: 400
